//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 05:19:06 下午 TST 
//


package com.tw.TWCrsXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorrectableOrganisationParty_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorrectableOrganisationParty_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oecd:ties:crs:v1}ReportingFIParty_Type">
 *       &lt;sequence>
 *         &lt;element name="DocSpec" type="{urn:oecd:ties:stf:v4}DocSpec_Type"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrectableOrganisationParty_Type", propOrder = {
    "docSpec"
})
public class CorrectableOrganisationPartyType
    extends ReportingFIPartyType
{
	
	public static void main(String[] args) {
		//---------------------------------申報金融機構----------------------------------------------
		CorrectableOrganisationPartyType correctableOrganisationPartyType = new CorrectableOrganisationPartyType();
		//------------------------------------------------------------------
		correctableOrganisationPartyType.getIN();
		correctableOrganisationPartyType.getResCountryCode();
		correctableOrganisationPartyType.getName();
		correctableOrganisationPartyType.getAddress();
		//-------------------------------------------------------------------
		DocSpecType docSpecType = new DocSpecType();
		correctableOrganisationPartyType.setDocSpec(docSpecType);
		correctableOrganisationPartyType.getDocSpec();
	
	}

    @XmlElement(name = "DocSpec", required = true)
    protected DocSpecType docSpec;

    /**
     * Gets the value of the docSpec property.
     * 
     * @return
     *     possible object is
     *     {@link DocSpecType }
     *     
     */
    public DocSpecType getDocSpec() {
        return docSpec;
    }

    /**
     * Sets the value of the docSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocSpecType }
     *     
     */
    public void setDocSpec(DocSpecType value) {
        this.docSpec = value;
    }

}
