//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 05:19:06 ¤U¤È TST 
//


package com.tw.TWCrsXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Payment_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{urn:oecd:ties:crs:v1}CrsPaymentType_EnumType"/>
 *         &lt;element name="PaymentAmnt" type="{urn:oecd:ties:TWcommontypesfatcacrs:v1}MonAmnt_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment_Type", propOrder = {
    "type",
    "paymentAmnt"
})
public class PaymentType {
	
	public static void main(String[] args) {
		PaymentType paymentType = new PaymentType();
		//-------------------------------------------
		paymentType.setType(CrsPaymentTypeEnumType.CRS_501);
		paymentType.getPaymentAmnt();
		//---------------------------------------------
		MonAmntType monAmntType = new MonAmntType();
		paymentType.setPaymentAmnt(monAmntType);
		paymentType.getPaymentAmnt();
	}

    @XmlElement(name = "Type", required = true)
    protected CrsPaymentTypeEnumType type;
    @XmlElement(name = "PaymentAmnt", required = true)
    protected MonAmntType paymentAmnt;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CrsPaymentTypeEnumType }
     *     
     */
    public CrsPaymentTypeEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrsPaymentTypeEnumType }
     *     
     */
    public void setType(CrsPaymentTypeEnumType value) {
        this.type = value;
    }

    /**
     * Gets the value of the paymentAmnt property.
     * 
     * @return
     *     possible object is
     *     {@link MonAmntType }
     *     
     */
    public MonAmntType getPaymentAmnt() {
        return paymentAmnt;
    }

    /**
     * Sets the value of the paymentAmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonAmntType }
     *     
     */
    public void setPaymentAmnt(MonAmntType value) {
        this.paymentAmnt = value;
    }

}
