//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 05:18:18 ¤U¤È TST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oecd:ties:TWcommontypesfatcacrs:v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tw.TWCommonTypes;
