//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 05:19:06 ¤U¤È TST 
//


package com.tw.TWCrsXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountHolder_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountHolder_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Individual" type="{urn:oecd:ties:crs:v1}PersonParty_Type"/>
 *           &lt;sequence>
 *             &lt;element name="Organisation" type="{urn:oecd:ties:crs:v1}OrganisationParty_Type"/>
 *             &lt;element name="AcctHolderType" type="{urn:oecd:ties:crs:v1}CrsAcctHolderType_EnumType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountHolder_Type", propOrder = {
    "individual",
    "organisation",
    "acctHolderType"
})
public class AccountHolderType {
	public static void main(String[] args) {
		AccountHolderType accountHolderType = new AccountHolderType();
		//------------------------------------------------------------------
		PersonPartyType partyType= new PersonPartyType();
		accountHolderType.setIndividual(partyType);
		accountHolderType.getIndividual();
		//-----------------------------------------------------------------
		OrganisationPartyType organisationPartyType = new OrganisationPartyType();
		accountHolderType.setOrganisation(organisationPartyType);
		accountHolderType.getOrganisation();
		//------------------------------------------------------------------
		accountHolderType.setAcctHolderType(CrsAcctHolderTypeEnumType.CRS_981);
		accountHolderType.getAcctHolderType();
	}

    @XmlElement(name = "Individual")
    protected PersonPartyType individual;
    @XmlElement(name = "Organisation")
    protected OrganisationPartyType organisation;
    @XmlElement(name = "AcctHolderType")
    protected CrsAcctHolderTypeEnumType acctHolderType;

    /**
     * Gets the value of the individual property.
     * 
     * @return
     *     possible object is
     *     {@link PersonPartyType }
     *     
     */
    public PersonPartyType getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonPartyType }
     *     
     */
    public void setIndividual(PersonPartyType value) {
        this.individual = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationPartyType }
     *     
     */
    public OrganisationPartyType getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationPartyType }
     *     
     */
    public void setOrganisation(OrganisationPartyType value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the acctHolderType property.
     * 
     * @return
     *     possible object is
     *     {@link CrsAcctHolderTypeEnumType }
     *     
     */
    public CrsAcctHolderTypeEnumType getAcctHolderType() {
        return acctHolderType;
    }

    /**
     * Sets the value of the acctHolderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrsAcctHolderTypeEnumType }
     *     
     */
    public void setAcctHolderType(CrsAcctHolderTypeEnumType value) {
        this.acctHolderType = value;
    }

}
