//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 05:19:06 ¤U¤È TST 
//


package com.tw.TWCrsXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrsBody_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CrsBody_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportingFI" type="{urn:oecd:ties:crs:v1}CorrectableOrganisationParty_Type"/>
 *         &lt;element name="ReportingGroup">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccountReport" type="{urn:oecd:ties:crs:v1}CorrectableAccountReport_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrsBody_Type", propOrder = {
    "reportingFI",
    "reportingGroup"
})
public class CrsBodyType {
	public static void main(String[] args) {
	CrsBodyType crsBodyType = new CrsBodyType();
	//---------------------------------------------
	CorrectableOrganisationPartyType correctableOrganisationPartyType = new CorrectableOrganisationPartyType();
	crsBodyType.setReportingFI(correctableOrganisationPartyType);
	crsBodyType.getReportingFI();
	//-----------------------------------------------
	CrsBodyType.ReportingGroup reportingGroup = new CrsBodyType.ReportingGroup();
	crsBodyType.setReportingGroup(reportingGroup);
	crsBodyType.getReportingGroup();

	
		
	}

    @XmlElement(name = "ReportingFI", required = true)
    protected CorrectableOrganisationPartyType reportingFI;
    @XmlElement(name = "ReportingGroup", required = true)
    protected CrsBodyType.ReportingGroup reportingGroup;

    /**
     * Gets the value of the reportingFI property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectableOrganisationPartyType }
     *     
     */
    public CorrectableOrganisationPartyType getReportingFI() {
        return reportingFI;
    }

    /**
     * Sets the value of the reportingFI property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectableOrganisationPartyType }
     *     
     */
    public void setReportingFI(CorrectableOrganisationPartyType value) {
        this.reportingFI = value;
    }

    /**
     * Gets the value of the reportingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link CrsBodyType.ReportingGroup }
     *     
     */
    public CrsBodyType.ReportingGroup getReportingGroup() {
        return reportingGroup;
    }

    /**
     * Sets the value of the reportingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrsBodyType.ReportingGroup }
     *     
     */
    public void setReportingGroup(CrsBodyType.ReportingGroup value) {
        this.reportingGroup = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AccountReport" type="{urn:oecd:ties:crs:v1}CorrectableAccountReport_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountReport"
    })
    public static class ReportingGroup {
    	public static void main(String[] args) {
			ReportingGroup reportingGroup = new ReportingGroup();
			CorrectableAccountReportType correctableAccountReportType = new CorrectableAccountReportType();
			reportingGroup.getAccountReport().add(correctableAccountReportType);
		}

        @XmlElement(name = "AccountReport")
        protected List<CorrectableAccountReportType> accountReport;

        /**
         * Gets the value of the accountReport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accountReport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccountReport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CorrectableAccountReportType }
         * 
         * 
         */
        public List<CorrectableAccountReportType> getAccountReport() {
            if (accountReport == null) {
                accountReport = new ArrayList<CorrectableAccountReportType>();
            }
            return this.accountReport;
        }

    }

}
