//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 05:19:06 ¤U¤È TST 
//


package com.tw.TWCrsXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Account number definition  
 * 
 * <p>Java class for FIAccountNumber_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FIAccountNumber_Type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="AcctNumberType" type="{urn:oecd:ties:TWcommontypesfatcacrs:v1}AcctNumberType_EnumType" />
 *       &lt;attribute name="UndocumentedAccount" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ClosedAccount" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FIAccountNumber_Type", propOrder = {
    "value"
})
public class FIAccountNumberType {
	public static void main(String[] args) {
		FIAccountNumberType fiAccountNumberType = new FIAccountNumberType();
		//-------------------------------------------------------------------
		fiAccountNumberType.setValue("±b¸¹");
		fiAccountNumberType.getValue();
		//-------------------------------------------------------------------
		fiAccountNumberType.setAcctNumberType(AcctNumberTypeEnumType.OECD_601);
		fiAccountNumberType.getValue();
		//-------------------------------------------------------------------
		fiAccountNumberType.setUndocumentedAccount(false);
		fiAccountNumberType.isUndocumentedAccount();
		//-------------------------------------------------------------------
		fiAccountNumberType.setClosedAccount(false);
		fiAccountNumberType.isClosedAccount();
		
	}

    @XmlValue
    protected String value;
    @XmlAttribute(name = "AcctNumberType")
    protected AcctNumberTypeEnumType acctNumberType;
    @XmlAttribute(name = "UndocumentedAccount")
    protected Boolean undocumentedAccount;
    @XmlAttribute(name = "ClosedAccount")
    protected Boolean closedAccount;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the acctNumberType property.
     * 
     * @return
     *     possible object is
     *     {@link AcctNumberTypeEnumType }
     *     
     */
    public AcctNumberTypeEnumType getAcctNumberType() {
        return acctNumberType;
    }

    /**
     * Sets the value of the acctNumberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctNumberTypeEnumType }
     *     
     */
    public void setAcctNumberType(AcctNumberTypeEnumType value) {
        this.acctNumberType = value;
    }

    /**
     * Gets the value of the undocumentedAccount property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUndocumentedAccount() {
        return undocumentedAccount;
    }

    /**
     * Sets the value of the undocumentedAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUndocumentedAccount(Boolean value) {
        this.undocumentedAccount = value;
    }

    /**
     * Gets the value of the closedAccount property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClosedAccount() {
        return closedAccount;
    }

    /**
     * Sets the value of the closedAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClosedAccount(Boolean value) {
        this.closedAccount = value;
    }

}
